services:
  hallmaster-database:
    image: postgres:16.8-alpine3.20
    container_name: hallmaster-database
    shm_size: 128mb
    restart: unless-stopped
    env_file:
      - secrets/database/.env.production
    volumes:
      - hallmaster-database:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - hallmaster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  hallmaster-backend:
    depends_on:
      hallmaster-database:
        condition: service_healthy
    image: hallmaster-backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: hallmaster-backend
    ports:
      - "3000:3000"
    env_file:
      - secrets/backend/.env.production
    networks:
      - hallmaster-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  hallmaster-frontend:
    depends_on:
      - hallmaster-backend
    image: hallmaster-frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: hallmaster-frontend
    ports:
      - "4411:4411"
    env_file:
      - secrets/frontend/.env.production
    networks:
      - hallmaster-network

networks:
  hallmaster-network:

volumes:
  hallmaster-database:
