services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: hallmaster-postgres
    shm_size: 128mb
    restart: unless-stopped
    env_file:
      - .env.production.local
    volumes:
      - hallmaster-database:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - hallmaster-network

  backend:
    image: hallmaster-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hallmaster-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    networks:
      - hallmaster-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: unless-stopped

networks:
  hallmaster-network:

volumes:
  hallmaster-database:
