services:
  hallmaster-postgres:
    image: postgres:16.8-alpine3.20
    container_name: hallmaster-postgres
    shm_size: 128mb
    restart: unless-stopped
    env_file:
      - .env.production.local
    volumes:
      - hallmaster-database:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - hallmaster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  hallmaster-backend:
    depends_on:
      hallmaster-postgres:
        condition: service_healthy
    image: hallmaster-backend
    build:
      context: ../..
      dockerfile: packages/backend/Dockerfile
    container_name: hallmaster-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    networks:
      - hallmaster-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

networks:
  hallmaster-network:

volumes:
  hallmaster-database:
