name: Backend CI

on:
  push:
    branches:
      - dev
    paths:
      - "packages/backend/**"
  pull_request:
    paths:
      - "packages/backend/**"

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-lint-and-format:
    name: Check lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./packages/backend
        run: pnpm install --filter=@hallmaster/backend --frozen-lockfile

      - name: Generate Prisma types
        working-directory: ./packages/backend
        run: pnpm --filter=@hallmaster/backend prisma:generate

      - name: Run lint
        working-directory: ./packages/backend
        run: pnpm --filter=@hallmaster/backend lint

      - name: Run format check
        working-directory: ./packages/backend
        run: pnpm --filter=@hallmaster/backend format

      - name: Test the build process
        working-directory: ./packages/backend
        run: pnpm build

  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs:
      - check-lint-and-format

    environment: Backend CI

    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install trusted certificat
        run: |
          sudo mkdir -p /usr/local/share/ca-certificates/

          echo "${{ secrets.REGISTRY_CA_CERT }}" > public-key.crt
          sudo cp public-key.crt /usr/local/share/ca-certificates/ca.crt
          sudo update-ca-certificates

          # Install into Docker trust directory
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY_HOST }}
          sudo cp public-key.crt /etc/docker/certs.d/${{ secrets.REGISTRY_HOST }}/ca.crt

      - name: Place CA for BuildKit
        run: |
          mkdir -p ${{ github.workspace }}/buildkit-certs
          echo "${{ secrets.REGISTRY_CA_CERT }}" | tr -d '\r' > ${{ github.workspace }}/buildkit-certs/ca.crt

      - name: Create buildkit config
        run: |
          mkdir -p ${{ github.workspace }}/buildkit-config
          cat <<-EOF > ${{ github.workspace }}/buildkit-config/buildkitd.toml
          [registry."${{ secrets.REGISTRY_HOST }}"]
            insecure = true
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: ${{ github.workspace }}/buildkit-config/buildkitd.toml
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to private Docker image registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ secrets.REGISTRY_HOST }}/hallmaster/backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/dev' }}
            type=sha,format=short

      - name: Build and push image (backend)
        uses: docker/build-push-action@v6.19.2
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy backend via HTTP
        run: |
          curl --insecure -X POST "http://${{ secrets.REGISTRY_HOST }}:9090/deploy" \
              -H "Authorization: Basic $(echo '${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_PASSWORD }}' | base64)" \
              -H "X-Registry-Host: ${{ secrets.REGISTRY_HOST }}" \
              --data '' -iL
